[variables]
NIXPACKS_NODE_VERSION = "22"

[phases.setup]
nixPkgs = ["bun"]

[phases.install]
cmds = ["cd frontend && bun install"]

[phases.build]
cmds = ["cd frontend && bun run build", "cp data/simpsonizado.db frontend/dist/simpsonizado.db"]

[start]
cmd = "cd frontend && DATABASE_PATH=./dist/simpsonizado.db bun ./dist/server/entry.mjs"
